### ISSUE TITLE
Maxbotix reporting impossible readings

### ISSUE THREAD

**Issue by mdbartos** [open-storm/perfect-cell#38]
For pull requests #35 and #37, `maxbotix_depth` is reporting measurements in the range of 46000-100000.

This issue occurs in both PRs, despite the fact that both PRs are independent. PR #37 only makes modifications to the atlas water quality sensor and the jenkinsfile.

We think that it's most likely some kind of memory overflow issue.

The issue doesn't seem to affect the most recent commit on the development branch.

**Comment by mdbartos** [comment]
@imondrag seems to have found the issue (and it looks like its a very old bug).

In debug mode, the `depth` buffer was showing a value of '1739', but `strtof` was converting it to 17398.

The char buffer for the depth reading, `char depth[4]`, is being initialized to a length of 4 without a terminating null byte. It should be 5 bytes long with a terminating null character. `strtof` will keep reading adjacent memory addresses until it finds a null byte.

Note that this issue affects basically all of our deployed nodes, although we haven't seen the symptoms until recently.

**Comment by imondrag** [comment]
This issue has been resolved in PR #35, with added support to invalidate readings based on which sensor is being used. Invalid short range readings will be -5000, and invalid long range readings will be -9999.
